name: wine-platform-9-staging-core22
adopt-info: wine
summary: wine platform snap it provides staging WINE 9 for snaps
description: |
 This snap creates a WINE staging 9 via content sharing to be used by other snaps that are using WINE.

grade: stable
confinement: strict
architectures:
  - build-on: amd64
base: core22
compression: lzo

lint:
  # Snapcraft's `ldd` lint can't handle WINE PE format files,
  # So just make it quiet and also make builds a surprising amount faster
  ignore:
    - library:
        - opt/wine-staging/lib/wine/i386-unix/**
        - opt/wine-staging/lib64/wine/x86_64-unix/**

slots:
  wine-9-staging:
    interface: content
    source:
      read:
      - $SNAP/opt/wine-staging

parts:
  wine:
    plugin: nil
    build-packages:
      - dpkg
      - wget
    override-build: |
      craftctl default

      ARCH="$(dpkg --print-architecture)"

      if [ $(wget -qO- https://dl.winehq.org/wine-builds/ubuntu/dists/jammy/main/binary-amd64/ | grep wine-staging | tail -n1 | grep -c ~rc) -gt 0 ]; then
       WINE_VER="$(wget -qO- https://dl.winehq.org/wine-builds/ubuntu/dists/jammy/main/binary-amd64/ | grep wine-staging | sed 's|_| |g;s|~| |2' | awk '{print $5}' | tail -n1)"
      else
       WINE_VER="$(wget -qO- https://dl.winehq.org/wine-builds/ubuntu/dists/jammy/main/binary-amd64/ | grep wine-staging | sed 's|_| |g;s|~| |g' | awk '{print $5}' | tail -n1)"
      fi

      # set snap version
      craftctl set version="$WINE_VER"

      # wget and dpkg extract the wine debs
      ## supporting binaries which are arch-specific but the same filenames in both architectures so we only install the native architecture
      DEB_URLS="https://dl.winehq.org/wine-builds/ubuntu/dists/jammy/main/binary-${ARCH}/wine-staging_${WINE_VER}~jammy-1_${ARCH}.deb"

      ## wine loaders - this one is the native system architecture
      DEB_URLS="$DEB_URLS https://dl.winehq.org/wine-builds/ubuntu/dists/jammy/main/binary-${ARCH}/wine-staging-${ARCH}_${WINE_VER}~jammy-1_${ARCH}.deb"

      if [ "$ARCH" = "amd64" ]; then
        ## on amd64 builds we need to also bundle the i386 wine loaders
        DEB_URLS="$DEB_URLS https://dl.winehq.org/wine-builds/ubuntu/dists/jammy/main/binary-i386/wine-staging-i386_${WINE_VER}~jammy-1_i386.deb"
      fi

      for DEB_URL in ${DEB_URLS}; do
        DEB=$(basename "${DEB_URL}")
        echo "Downloading ${DEB_URL}..."
        wget --quiet "${DEB_URL}" -O "${CRAFT_PART_INSTALL}/${DEB}"
        echo "Unpacking ${DEB}..."
        dpkg -x "${CRAFT_PART_INSTALL}/${DEB}" ${CRAFT_PART_INSTALL}
        rm -f "${CRAFT_PART_INSTALL}/${DEB}"
      done

      # Cleanup
      rm -rf ${CRAFT_PART_INSTALL}/opt/wine-staging/share/applications
      rm -rf ${CRAFT_PART_INSTALL}/opt/wine-staging/share/man
      rm -rf ${CRAFT_PART_INSTALL}/usr

      # Disable winemenubuilder
      sed -i 's/winemenubuilder.exe -a -r/winemenubuilder.exe -r/g' "${CRAFT_PART_INSTALL}"/opt/wine-staging/share/wine/wine.inf
